use_frameworks!

target 'MHKeyboardToolbar_Example' do
  pod 'MHKeyboardToolbar', :path => '../'

#  target 'MHKeyboardToolbar_Tests' do
#    inherit! :search_paths
#
#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
#  end
end
